### ISSUE TITLE
ImportError: cannot import name 'printf' 

### ISSUE THREAD

**Issue by mflaxman10** [xnd-project/rbc#211]
Immediately upon attempting to import, get the error message below

from rbc.omniscidb import RemoteOmnisci

ImportError: cannot import name 'printf' from 'rbc.irtools' (/opt/conda/lib/python3.7/site-packages/rbc/irtools.py)

Tried with release and with github master
rbc-project-0.4.1+74.g447b0c7

**Comment by pearu** [comment]
The Python function `printf` is defined in `rbc/irtools.py`. Hence, this import error could be due to having `irtools.py` from some older version of rbc that did not have `printf` defined. The `printf` feature was introduced in rbc 0.3.0.

Try removing older versions of `rbc` from your Python installation and then reinstalling the latest rbc.

**Comment by pearu** [comment]
On another note, it looks like you are using conda but rbc is installed using pip. In a conda environment, the rbc should be installed via `conda install -c conda-forge rbc`.

**Comment by pearu** [comment]
Resolving as won't-fix because no feedback and the issue can be avoided when installing rbc properly.
