### ISSUE TITLE
Replace register_runtime_udf by register_runtime_extension_functions

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#67]
On [notebooks/omnisci-demo.ipynb](https://github.com/xnd-project/rbc/blob/master/notebooks/omnisci-demo.ipynb), one uses `register_runtime_udf` but this function is deprecated:

```
 Using register_runtime_udf is deprecated, use register_runtime_extension_functions instead.
```

**Comment by pearu** [comment]
It is not easy to `register_runtime_extension_functions` explicitly because of the signature is not passed as a string (as is in the `register_runtime_udf` case) but as a dictionary of codes that contains the signature type information.

We can move the advance section from the notebook to keep it simple.

**Comment by guilhermeleobas** [comment]
`register_runtime_udf` was removed from the [notebook](https://github.com/xnd-project/rbc/blob/master/notebooks/rbc-omnisci-udf.ipynb)
